### ISSUE TITLE
File list doesn't work

### ISSUE THREAD

**Issue by dloukola** [crimdon/SQLToolkitAzure#16]
## Run SQL Scripts on azure
File containing list of files to execute (optional), if supplied, the task cannot run. Throws error:

`##[error]System.Management.Automation.ParameterBindingValidationException: Cannot bind argument to parameter 'Path' because it is null.`

**Comment by crimdon** [comment]
Thanks for reporting this. Will get on to it as soon as I get a chance

**Comment by crimdon** [comment]
Fixed in latest release

**Comment by ian-a-anderson** [comment]
FYI, it looks like you re-introduced this bug... the current code still shows:  
[String] [Parameter(Mandatory = $true)] $executionOrder

Seems like a subsequent commit may have inadvertently removed the "Mandatory = $false" fix?

**Comment by crimdon** [comment]
Sorry about that. Fixed now
